#!/bin/sh

if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
  # Wayland environment
  qrencode -t PNG -s 16 -o /tmp/tmp.png $(wl-paste)
else
  # X11 environment
  qrencode -t PNG -s 16 -o /tmp/tmp.png $(xclip -o -sel)
fi

nsxiv /tmp/tmp.png
