#!/bin/sh
output='/home/fdan/pix/screenshots/%Y%m%d_%H%M%S.png'

case "$1" in
	"select") file=$(date +"$output")
		scrot "$file" --select --line mode=edge || exit ;;
	"window") file=$(date +"$output")
		scrot "$file" --focused --border || exit ;;
	*) file=$(date +"$output")
		scrot "$file" || exit ;;
esac

xclip -selection clipboard -t image/png -i "$file"
notify-send "Screenshot taken"
