#!/bin/sh

setxkbmap -option caps:escape
xcape -e "Control_L=Escape"
xset r rate 300 50
xrandr --dpi 96 																										# Set DPI. User may want to use a larger number for larger screens.
xwallpaper --zoom ~/.local/share/bg
# redshift -O 4500
syncthing -no-browser &
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup

autostart="mpd picom dunst unclutter pipewire dwmbar"

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
