[mgr]
prepend_keymap = [
  { on = [ "T" ], run = 'shell "nsxiv -t ."' },
  # shortcut
  { on = [ "g", "k" ], run = "cd ~/sync/manga/local", desc = "Go comic" },
  { on = [ "g", "D" ], run = "cd ~/dox", desc = "Go documents" },
  { on = [ "g", "p" ], run = "cd ~/pix", desc = "Go pictures" },
  { on = [ "g", "n" ], run = "cd ~/sync/note", desc = "Go notes" },
  { on = [ "g", "w" ], run = "cd ~/pix/wallpapers", desc = "Go wallpapers" },
  { on = [ "g", "s" ], run = "cd ~/pix/screenshots", desc = "Go screenshots" },
  { on = [ "g", "v" ], run = "cd ~/vids", desc = "Go videos" },
  { on = [ "g", "t" ], run = "cd ~/.local/share/Trash/files", desc = "Go trash" }
]
