[mgr]
ratio = [1, 2, 3]

[[opener.set-wallpaper]]
run  = "killall swaybg; ln -s -f %s1 ~/.bg; swaybg -m fill -i ~/.bg"
for  = "linux"
desc = "Set as wallpaper"
orphan = true

[[open.prepend_rules]]
mime = "image/*"
use  = [ "set-wallpaper", "open" ]
