term=foot
title=foot

font=monospace:size=14

pad=8x8

dpi-aware=no

[csd]
preferred=none

[cursor]
style=block
blink=yes

# gruvbox dark — matches kitty/kitty.conf
[colors-dark]
alpha=1
background=282828
foreground=ebdbb2

# black
regular0 = 282828
bright0  = 928374

# red
regular1 = fb4934
bright1  = cc241d

# green
regular2 = b8bb26
bright2  = 98971a

# yellow
regular3 = fabd2d
bright3  = d79921

# blue
regular4 = 83a598
bright4  = 458588

# magenta
regular5 = d3869b
bright5  = b16286

# cyan
regular6 = 8ec07c
bright6  = 689d6a

# white
regular7 = a89984
bright7  = 928374
